import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  // Create users
  const hashedPassword = await bcrypt.hash('password123', 10);
  const users = await Promise.all([
    prisma.user.create({
      data: {
        username: 'john_doe',
        email: 'john@example.com',
        password: hashedPassword,
      },
    }),
    prisma.user.create({
      data: {
        username: 'jane_smith',
        email: 'jane@example.com',
        password: hashedPassword,
      },
    }),
  ]);

  // Create posts with post details
  const posts = await Promise.all([
    prisma.post.create({
      data: {
        title: "A Great Apartment Next to the Beach!",
        images: ["https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1000,
        address: "456 Park Avenue",
        city: "London",
        latitude: "51.5074",
        longitude: "-0.1278",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Beautiful apartment with ocean view",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 80,
            school: 2,
            bus: 1,
            restaurant: 3,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "An Awesome Apartment Near the Park!",
        images: ["https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 152800,
        address: "789 Oxford Street",
        city: "London",
        latitude: "52.4862",
        longitude: "-1.8904",
        type: "buy",
        property: "house",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Spacious house with a beautiful garden",
            utilities: "All included",
            pet: "Not allowed",
            size: 120,
            school: 1,
            bus: 2,
            restaurant: 4,
          },
        },
      },
    }),
    // Additional 15 apartments
    prisma.post.create({
      data: {
        title: "Cozy Studio in Bangkok",
        images: ["https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 500,
        address: "123 Sukhumvit Road",
        city: "Bangkok",
        latitude: "13.7563",
        longitude: "100.5018",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Modern studio in the heart of Bangkok",
            utilities: "Electricity, Water, Internet",
            pet: "Not allowed",
            size: 40,
            school: 1,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Luxurious Condo with River View",
        images: ["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 2000,
        address: "456 Charoenkrung Road",
        city: "Bangkok",
        latitude: "13.7246",
        longitude: "100.5150",
        type: "rent",
        property: "condo",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Spacious condo with stunning views of the Chao Phraya River",
            utilities: "All included",
            pet: "Allowed",
            size: 150,
            school: 2,
            bus: 1,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Charming Apartment in Florence",
        images: ["https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1200,
        address: "789 Via dei Neri",
        city: "Florence",
        latitude: "43.7696",
        longitude: "11.2558",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Beautiful apartment in the historic center of Florence",
            utilities: "Electricity, Gas, Water",
            pet: "Not allowed",
            size: 70,
            school: 1,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Modern Loft in Milan",
        images: ["https://images.pexels.com/photos/9565787/pexels-photo-9565787.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 1500,
        address: "101 Via Tortona",
        city: "Milan",
        latitude: "45.4642",
        longitude: "9.1900",
        type: "rent",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Stylish loft in Milan's design district",
            utilities: "All included",
            pet: "Allowed",
            size: 80,
            school: 1,
            bus: 3,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Beachfront Condo in Phuket",
        images: ["https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 1800,
        address: "222 Kata Beach Road",
        city: "Phuket",
        latitude: "7.8208",
        longitude: "98.3030",
        type: "rent",
        property: "condo",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Luxurious condo with direct access to Kata Beach",
            utilities: "Electricity, Water",
            pet: "Not allowed",
            size: 100,
            school: 1,
            bus: 1,
            restaurant: 3,
          },
        },
      },
    }),
    // Add 10 more apartments here with varied locations
    prisma.post.create({
      data: {
        title: "Stylish Apartment in Rome",
        images: ["https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1800,
        address: "123 Via del Corso",
        city: "Rome",
        latitude: "41.9028",
        longitude: "12.4964",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Elegant apartment in the heart of Rome",
            utilities: "All included",
            pet: "Not allowed",
            size: 90,
            school: 2,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Chiang Mai Old City Condo",
        images: ["https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 600,
        address: "456 Ratchadamnoen Road",
        city: "Chiang Mai",
        latitude: "18.7883",
        longitude: "98.9853",
        type: "rent",
        property: "condo",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Cozy condo in Chiang Mai's historic old city",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 50,
            school: 1,
            bus: 2,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Parisian Charm in Montmartre",
        images: ["https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 2200,
        address: "789 Rue des Abbesses",
        city: "Paris",
        latitude: "48.8566",
        longitude: "2.3522",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Charming apartment with a view of Sacré-Cœur",
            utilities: "Electricity, Gas, Water",
            pet: "Not allowed",
            size: 75,
            school: 2,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Barcelona Gothic Quarter Flat",
        images: ["https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 1600,
        address: "101 Carrer de Ferran",
        city: "Barcelona",
        latitude: "41.3851",
        longitude: "2.1734",
        type: "rent",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Historic flat in the heart of Barcelona's Gothic Quarter",
            utilities: "All included",
            pet: "Allowed",
            size: 60,
            school: 1,
            bus: 4,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Manhattan Luxury Apartment",
        images: ["https://images.pexels.com/photos/2555635/pexels-photo-2555635.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 5000,
        address: "555 Park Avenue",
        city: "New York",
        latitude: "40.7128",
        longitude: "-74.0060",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Luxurious apartment with Central Park views",
            utilities: "All included",
            pet: "Allowed",
            size: 150,
            school: 3,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Modern Tokyo Studio",
        images: ["https://images.pexels.com/photos/1571459/pexels-photo-1571459.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 1800,
        address: "2-1-1 Nihonbashi",
        city: "Tokyo",
        latitude: "35.6762",
        longitude: "139.6503",
        type: "rent",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Sleek studio in the bustling Nihonbashi district",
            utilities: "Electricity, Water, Internet",
            pet: "Not allowed",
            size: 40,
            school: 2,
            bus: 5,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Sydney Harbour View Apartment",
        images: ["https://images.pexels.com/photos/2079234/pexels-photo-2079234.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 2800,
        address: "33 Circular Quay West",
        city: "Sydney",
        latitude: "-33.8688",
        longitude: "151.2093",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Stunning apartment with views of Sydney Opera House",
            utilities: "All included",
            pet: "Allowed",
            size: 100,
            school: 2,
            bus: 3,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Berlin Mitte Loft",
        images: ["https://images.pexels.com/photos/1571472/pexels-photo-1571472.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1400,
        address: "123 Friedrichstraße",
        city: "Berlin",
        latitude: "52.5200",
        longitude: "13.4050",
        type: "rent",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Spacious loft in Berlin's trendy Mitte district",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 85,
            school: 1,
            bus: 4,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Dubai Marina Penthouse",
        images: ["https://images.pexels.com/photos/2096983/pexels-photo-2096983.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 3,
        price: 4500,
        address: "1 Marina Promenade",
        city: "Dubai",
        latitude: "25.2048",
        longitude: "55.2708",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Luxurious penthouse with panoramic views of Dubai Marina",
            utilities: "All included",
            pet: "Allowed",
            size: 200,
            school: 3,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Vancouver Downtown Condo",
        images: ["https://images.pexels.com/photos/2079246/pexels-photo-2079246.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 2000,
        address: "789 Robson Street",
        city: "Vancouver",
        latitude: "49.2827",
        longitude: "-123.1207",
        type: "rent",
        property: "condo",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Modern condo in the heart of downtown Vancouver",
            utilities: "Electricity, Water, Internet",
            pet: "Not allowed",
            size: 65,
            school: 2,
            bus: 5,
            restaurant: 4,
          },
        },
      },
    }),
    // Adding 10 more apartments
    prisma.post.create({
      data: {
        title: "Sunny Apartment in Lisbon",
        images: ["https://images.pexels.com/photos/12639296/pexels-photo-12639296.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1500,
        address: "123 Rua da Liberdade",
        city: "Lisbon",
        latitude: "38.7223",
        longitude: "-9.1393",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Charming apartment in the heart of Lisbon",
            utilities: "Electricity, Water, Internet",
            pet: "Allowed",
            size: 85,
            school: 2,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Cozy Cabin in the Swiss Alps",
        images: ["https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 2500,
        address: "456 Mountain Road",
        city: "Zermatt",
        latitude: "46.0207",
        longitude: "7.7491",
        type: "rent",
        property: "apartment",
        userId: users[1].id,
        postDetail: {

          create: {
            desc: "Beautiful cabin with stunning mountain views",
            utilities: "Electricity, Water, Heating",
            pet: "Allowed",
            size: 120,
            school: 1,
            bus: 2,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Chic Apartment in Buenos Aires",
        images: ["https://images.pexels.com/photos/5997967/pexels-photo-5997967.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 1,
        bathroom: 1,
        price: 800,
        address: "789 Avenida de Mayo",
        city: "Buenos Aires",
        latitude: "-34.6037",
        longitude: "-58.3816",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Stylish apartment in the vibrant city center",
            utilities: "Electricity, Water, Internet",
            pet: "Not allowed",
            size: 50,
            school: 1,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Traditional House in Kyoto",
        images: ["https://images.pexels.com/photos/5998120/pexels-photo-5998120.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1200,
        address: "123 Hanami Street",
        city: "Kyoto",
        latitude: "35.0116",
        longitude: "135.7681",
        type: "rent",
        property: "house",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Traditional Japanese house with a beautiful garden",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 80,
            school: 1,
            bus: 2,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Modern Apartment in Toronto",
        images: ["https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 2200,
        address: "456 Queen Street",
        city: "Toronto",
        latitude: "43.65107",
        longitude: "-79.347015",
        type: "rent",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Contemporary apartment in downtown Toronto",
            utilities: "Electricity, Water, Internet",
            pet: "Not allowed",
            size: 90,
            school: 2,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Luxurious Penthouse in Manhattan",
        images: ["https://images.pexels.com/photos/2459/stairs-home-loft-lifestyle.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 4,
        bathroom: 3,
        price: 2500000,
        address: "123 Park Avenue",
        city: "New York",
        latitude: "40.7128",
        longitude: "-74.0060",
        type: "buy",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Stunning penthouse with panoramic views of Central Park",
            utilities: "All included",
            pet: "Allowed",
            size: 300,
            school: 3,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Elegant Apartment in Paris",
        images: ["https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 1800000,
        address: "456 Champs-Élysées",
        city: "Paris",
        latitude: "48.8566",
        longitude: "2.3522",
        type: "buy",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Luxurious apartment with a view of the Eiffel Tower",
            utilities: "Electricity, Water, Gas",
            pet: "Not allowed",
            size: 180,
            school: 2,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Modern Loft in Downtown Los Angeles",
        images: ["https://images.pexels.com/photos/298842/pexels-photo-298842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 950000,
        address: "789 Grand Avenue",
        city: "Los Angeles",
        latitude: "34.0522",
        longitude: "-118.2437",
        type: "buy",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Spacious loft in the heart of DTLA",
            utilities: "All included",
            pet: "Allowed",
            size: 150,
            school: 1,
            bus: 4,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Waterfront Apartment in Sydney",
        images: ["https://images.pexels.com/photos/3167175/pexels-photo-3167175.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 2200000,
        address: "101 Circular Quay",
        city: "Sydney",
        latitude: "-33.8688",
        longitude: "151.2093",
        type: "buy",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Luxurious apartment with stunning views of Sydney Harbour",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 200,
            school: 2,
            bus: 3,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Historic Apartment in Rome",
        images: ["https://images.pexels.com/photos/258184/pexels-photo-258184.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 1,
        price: 1200000,
        address: "234 Via del Corso",
        city: "Rome",
        latitude: "41.9028",
        longitude: "12.4964",
        type: "buy",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Charming apartment in a historic building near the Colosseum",
            utilities: "Electricity, Gas, Water",
            pet: "Not allowed",
            size: 110,
            school: 1,
            bus: 3,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Luxury Condo in Miami Beach",
        images: ["https://images.pexels.com/photos/221506/pexels-photo-221506.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 3,
        price: 1750000,
        address: "567 Ocean Drive",
        city: "Miami",
        latitude: "25.7617",
        longitude: "-80.1918",
        type: "buy",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Stunning beachfront condo with private balcony",
            utilities: "All included",
            pet: "Allowed",
            size: 220,
            school: 2,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Skyline Apartment in Hong Kong",
        images: ["https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 1900000,
        address: "888 Victoria Harbour",
        city: "Hong Kong",
        latitude: "22.3193",
        longitude: "114.1694",
        type: "buy",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "High-rise apartment with breathtaking views of Victoria Harbour",
            utilities: "Electricity, Water",
            pet: "Not allowed",
            size: 90,
            school: 3,
            bus: 4,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Riverside Apartment in London",
        images: ["https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 3,
        bathroom: 2,
        price: 2100000,
        address: "45 Thames Street",
        city: "London",
        latitude: "51.5074",
        longitude: "-0.1278",
        type: "buy",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Elegant apartment with views of the River Thames",
            utilities: "All included",
            pet: "Allowed",
            size: 160,
            school: 2,
            bus: 3,
            restaurant: 4,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Beachfront Condo in Bali",
        images: ["https://images.pexels.com/photos/7534561/pexels-photo-7534561.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 2,
        bathroom: 2,
        price: 750000,
        address: "123 Kuta Beach Road",
        city: "Bali",
        latitude: "-8.6505",
        longitude: "115.2167",
        type: "buy",
        property: "apartment",
        userId: users[0].id,
        postDetail: {
          create: {
            desc: "Beautiful condo with direct access to Kuta Beach",
            utilities: "Electricity, Water",
            pet: "Allowed",
            size: 120,
            school: 1,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
    prisma.post.create({
      data: {
        title: "Penthouse in Downtown Dubai",
        images: ["https://images.pexels.com/photos/6058444/pexels-photo-6058444.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"],
        bedroom: 4,
        bathroom: 4,
        price: 3500000,
        address: "1 Sheikh Mohammed bin Rashid Blvd",
        city: "Dubai",
        latitude: "25.2048",
        longitude: "55.2708",
        type: "buy",
        property: "apartment",
        userId: users[1].id,
        postDetail: {
          create: {
            desc: "Opulent penthouse with panoramic views of the Burj Khalifa",
            utilities: "All included",
            pet: "Allowed",
            size: 400,
            school: 3,
            bus: 2,
            restaurant: 5,
          },
        },
      },
    }),
  ]);

  console.log('Seeding completed.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });